import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Nav from '../components/nav';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <main className={styles.main}>
        <h1 className={styles.title}>Codelab Next.js 2019</h1>
        <p className={styles.description}>양재동 코드랩 Next.js 2019 수업 결과물</p>
        <div className="text-container">
          <button className="btn btn-primary btn-large">바로 시작하기</button>
        </div>
      </main>
    </div>
  );
}
